// App.tsx

import React, { useState, useEffect, useCallback } from 'react';
import { 
  LayoutDashboard, 
  MessageSquare, 
  BarChart3, 
  Settings, 
  Zap, 
  Search, 
  Bell, 
  User,
  Plus,
  ArrowUpRight,
  Sparkles,
  Send,
  Loader2,
  BrainCircuit
} from 'lucide-react';
import { 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  BarChart,
  Bar,
  Cell
} from 'recharts';
import { analyzeContent, getSmartSuggestions } from './services/gemini';
import { Message, MetricData } from './types';

// Components
const SidebarItem = ({ icon: Icon, label, active, onClick }: { icon: any, label: string, active?: boolean, onClick: () => void }) => (
  <button 
    onClick={onClick}
    className={`flex items-center gap-3 w-full px-4 py-3 rounded-xl transition-all duration-200 group ${
      active ? 'bg-indigo-600/20 text-indigo-400 border border-indigo-500/20' : 'text-slate-400 hover:bg-white/5 hover:text-slate-100'
    }`}
  >
    <Icon size={20} className={active ? 'text-indigo-400' : 'text-slate-500 group-hover:text-slate-300'} />
    <span className="font-medium">{label}</span>
  </button>
);

const StatCard = ({ title, value, trend, icon: Icon }: { title: string, value: string, trend: number, icon: any }) => (
  <div className="glass p-6 rounded-2xl flex flex-col gap-4">
    <div className="flex justify-between items-start">
      <div className="p-3 bg-indigo-500/10 rounded-lg">
        <Icon size={22} className="text-indigo-400" />
      </div>
      <div className={`flex items-center gap-1 text-sm font-medium ${trend >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
        {trend >= 0 ? '+' : ''}{trend}%
        <ArrowUpRight size={14} className={trend < 0 ? 'rotate-90' : ''} />
      </div>
    </div>
    <div>
      <p className="text-slate-400 text-sm font-medium">{title}</p>
      <h3 className="text-2xl font-bold mt-1">{value}</h3>
    </div>
  </div>
);

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [prompt, setPrompt] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [isTyping, setIsTyping] = useState(false);
  const [suggestions, setSuggestions] = useState<any[]>([]);

  const chartData = [
    { name: 'Mon', value: 4000 },
    { name: 'Tue', value: 3000 },
    { name: 'Wed', value: 2000 },
    { name: 'Thu', value: 2780 },
    { name: 'Fri', value: 1890 },
    { name: 'Sat', value: 2390 },
    { name: 'Sun', value: 3490 },
  ];

  const handleSend = async () => {
    if (!prompt.trim()) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: prompt,
      timestamp: Date.now()
    };

    setMessages(prev => [...prev, userMsg]);
    setPrompt('');
    setIsTyping(true);

    try {
      const response = await analyzeContent(prompt);
      const assistantMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response,
        timestamp: Date.now()
      };
      setMessages(prev => [...prev, assistantMsg]);
    } catch (error) {
      console.error(error);
    } finally {
      setIsTyping(false);
    }
  };

  const fetchSuggestions = useCallback(async () => {
    const data = await getSmartSuggestions("Current productivity trends and project management optimization.");
    setSuggestions(data);
  }, []);

  useEffect(() => {
    fetchSuggestions();
  }, [fetchSuggestions]);

  return (
    <div className="flex h-screen overflow-hidden bg-[#030712]">
      {/* Sidebar */}
      <aside className="w-64 flex-shrink-0 border-r border-white/10 flex flex-col p-6 hidden md:flex">
        <div className="flex items-center gap-3 mb-10 px-2">
          <div className="bg-indigo-600 p-2 rounded-lg">
            <Zap size={24} className="text-white fill-current" />
          </div>
          <span className="text-xl font-bold font-outfit tracking-tight">Lumina AI</span>
        </div>

        <nav className="flex-1 space-y-2">
          <SidebarItem 
            icon={LayoutDashboard} 
            label="Dashboard" 
            active={activeTab === 'dashboard'} 
            onClick={() => setActiveTab('dashboard')} 
          />
          <SidebarItem 
            icon={MessageSquare} 
            label="AI Chat" 
            active={activeTab === 'chat'} 
            onClick={() => setActiveTab('chat')} 
          />
          <SidebarItem 
            icon={BarChart3} 
            label="Analytics" 
            active={activeTab === 'analytics'} 
            onClick={() => setActiveTab('analytics')} 
          />
          <SidebarItem 
            icon={BrainCircuit} 
            label="Insights" 
            active={activeTab === 'insights'} 
            onClick={() => setActiveTab('insights')} 
          />
        </nav>

        <div className="mt-auto pt-6 border-t border-white/5 space-y-2">
          <SidebarItem icon={Settings} label="Settings" onClick={() => {}} />
          <div className="p-4 glass rounded-xl mt-4">
            <p className="text-xs text-slate-500 font-bold uppercase tracking-wider mb-2">Storage</p>
            <div className="w-full bg-white/10 h-1.5 rounded-full overflow-hidden">
              <div className="bg-indigo-500 h-full w-3/4"></div>
            </div>
            <p className="text-[10px] text-slate-400 mt-2">7.2 GB of 10 GB used</p>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col min-w-0 overflow-y-auto">
        {/* Header */}
        <header className="h-20 border-b border-white/5 flex items-center justify-between px-8 bg-[#030712]/50 backdrop-blur-sm sticky top-0 z-30">
          <div className="flex items-center gap-4 bg-white/5 px-4 py-2 rounded-xl border border-white/10 w-full max-w-md">
            <Search size={18} className="text-slate-400" />
            <input 
              type="text" 
              placeholder="Search data, insights, or commands..." 
              className="bg-transparent border-none outline-none text-sm w-full text-slate-200 placeholder:text-slate-500"
            />
          </div>

          <div className="flex items-center gap-4">
            <button className="p-2.5 rounded-xl hover:bg-white/5 text-slate-400 transition-colors relative">
              <Bell size={20} />
              <span className="absolute top-2 right-2 w-2 h-2 bg-indigo-500 rounded-full"></span>
            </button>
            <div className="h-8 w-[1px] bg-white/10 mx-2"></div>
            <button className="flex items-center gap-3 pl-2 pr-1 py-1 rounded-full bg-white/5 border border-white/10 hover:border-white/20 transition-all">
              <span className="text-sm font-medium px-2">Alex Rivera</span>
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500 flex items-center justify-center">
                <User size={16} className="text-white" />
              </div>
            </button>
          </div>
        </header>

        {/* Dynamic Section Rendering */}
        <div className="p-8">
          {activeTab === 'dashboard' && (
            <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
              <div className="flex justify-between items-end">
                <div>
                  <h1 className="text-3xl font-bold font-outfit">Workspace Overview</h1>
                  <p className="text-slate-400 mt-1">Welcome back. Here's what's happening today.</p>
                </div>
                <button className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition-all shadow-lg shadow-indigo-600/20">
                  <Plus size={20} />
                  New Analysis
                </button>
              </div>

              {/* Stats Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <StatCard title="Active Users" value="24.8k" trend={12} icon={User} />
                <StatCard title="AI Operations" value="1.2M" trend={45} icon={Zap} />
                <StatCard title="Analysis Speed" value="142ms" trend={-8} icon={Sparkles} />
                <StatCard title="Revenue" value="$42,800" trend={22} icon={BarChart3} />
              </div>

              {/* Charts Row */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2 glass p-8 rounded-2xl">
                  <div className="flex justify-between items-center mb-8">
                    <h3 className="font-bold text-lg">System Performance</h3>
                    <select className="bg-white/5 border border-white/10 text-xs rounded-lg px-3 py-1.5 outline-none">
                      <option>Last 7 days</option>
                      <option>Last 30 days</option>
                    </select>
                  </div>
                  <div className="h-[300px] w-full">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={chartData}>
                        <defs>
                          <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#6366f1" stopOpacity={0.3}/>
                            <stop offset="95%" stopColor="#6366f1" stopOpacity={0}/>
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(255,255,255,0.05)" />
                        <XAxis 
                          dataKey="name" 
                          axisLine={false} 
                          tickLine={false} 
                          tick={{ fill: '#94a3b8', fontSize: 12 }} 
                          dy={10}
                        />
                        <YAxis 
                          axisLine={false} 
                          tickLine={false} 
                          tick={{ fill: '#94a3b8', fontSize: 12 }}
                        />
                        <Tooltip 
                          contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: '12px', color: '#fff' }}
                        />
                        <Area 
                          type="monotone" 
                          dataKey="value" 
                          stroke="#6366f1" 
                          strokeWidth={3}
                          fillOpacity={1} 
                          fill="url(#colorValue)" 
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </div>

                <div className="glass p-8 rounded-2xl">
                  <h3 className="font-bold text-lg mb-6">AI Suggestions</h3>
                  <div className="space-y-4">
                    {suggestions.length > 0 ? suggestions.map((s, i) => (
                      <div key={i} className="p-4 bg-white/5 rounded-xl border border-white/5 hover:border-white/10 transition-all cursor-pointer group">
                        <div className="flex items-center gap-3 mb-2">
                          <div className="p-2 bg-indigo-500/20 rounded-lg text-indigo-400 group-hover:bg-indigo-500 group-hover:text-white transition-all">
                            <Zap size={16} />
                          </div>
                          <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider">{s.type}</span>
                        </div>
                        <h4 className="font-semibold text-sm text-slate-200">{s.title}</h4>
                        <p className="text-xs text-slate-400 mt-1 line-clamp-2">{s.description}</p>
                      </div>
                    )) : (
                      <div className="flex flex-col items-center justify-center py-12 text-slate-500">
                        <Loader2 className="animate-spin mb-3" />
                        <p className="text-sm">Calculating insights...</p>
                      </div>
                    )}
                  </div>
                  <button className="w-full mt-6 py-2.5 border border-white/10 rounded-xl text-sm font-medium text-slate-400 hover:bg-white/5 transition-all">
                    View All Insights
                  </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'chat' && (
            <div className="h-[calc(100vh-12rem)] flex flex-col glass rounded-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-500">
              {/* Chat Messages */}
              <div className="flex-1 overflow-y-auto p-8 space-y-6 scroll-smooth">
                {messages.length === 0 ? (
                  <div className="h-full flex flex-col items-center justify-center text-center max-w-md mx-auto">
                    <div className="p-4 bg-indigo-600/20 rounded-3xl mb-6">
                      <BrainCircuit size={48} className="text-indigo-400" />
                    </div>
                    <h2 className="text-2xl font-bold mb-2 font-outfit">How can I assist you today?</h2>
                    <p className="text-slate-400">Ask Lumina AI to analyze your workspace metrics, generate strategy proposals, or debug technical workflows.</p>
                  </div>
                ) : (
                  messages.map((msg) => (
                    <div 
                      key={msg.id} 
                      className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                    >
                      <div className={`max-w-[80%] p-4 rounded-2xl flex flex-col gap-1 ${
                        msg.role === 'user' 
                          ? 'bg-indigo-600 text-white rounded-tr-none' 
                          : 'bg-white/5 border border-white/10 text-slate-200 rounded-tl-none'
                      }`}>
                        <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                        <span className="text-[10px] opacity-50 self-end mt-1">
                          {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </span>
                      </div>
                    </div>
                  ))
                )}
                {isTyping && (
                  <div className="flex justify-start">
                    <div className="bg-white/5 border border-white/10 p-4 rounded-2xl rounded-tl-none flex items-center gap-2">
                      <div className="w-1.5 h-1.5 bg-indigo-400 rounded-full animate-bounce"></div>
                      <div className="w-1.5 h-1.5 bg-indigo-400 rounded-full animate-bounce delay-75"></div>
                      <div className="w-1.5 h-1.5 bg-indigo-400 rounded-full animate-bounce delay-150"></div>
                    </div>
                  </div>
                )}
              </div>

              {/* Chat Input */}
              <div className="p-6 border-t border-white/10 bg-black/20 backdrop-blur-xl">
                <div className="relative flex items-center gap-4">
                  <div className="flex-1 relative">
                    <input 
                      type="text" 
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                      placeholder="Type a message or command..." 
                      className="w-full bg-white/5 border border-white/10 rounded-xl px-6 py-4 pr-16 outline-none focus:border-indigo-500/50 transition-all text-slate-200"
                    />
                    <div className="absolute right-4 top-1/2 -translate-y-1/2 flex items-center gap-2">
                      <button className="p-2 text-slate-400 hover:text-white transition-colors">
                        <Sparkles size={18} />
                      </button>
                    </div>
                  </div>
                  <button 
                    onClick={handleSend}
                    disabled={!prompt.trim() || isTyping}
                    className="p-4 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:hover:bg-indigo-600 rounded-xl text-white transition-all shadow-lg shadow-indigo-600/20"
                  >
                    <Send size={20} />
                  </button>
                </div>
              </div>
            </div>
          )}

          {(activeTab === 'analytics' || activeTab === 'insights') && (
            <div className="h-full flex flex-col items-center justify-center py-20 text-center animate-pulse">
              <BarChart3 size={64} className="text-slate-800 mb-6" />
              <h2 className="text-xl font-bold text-slate-600">Modules loading...</h2>
              <p className="text-slate-500 mt-2 max-w-xs mx-auto">This section is being synchronized with your real-time data clusters.</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default App;

// app.component.ts

import { Component, signal, effect, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { GeminiService } from './services/gemini.service.ts';
import { Message } from './types.ts';
import { SidebarComponent } from './components/sidebar.component.ts';
import { HeaderComponent } from './components/header.component.ts';
import { ClientNavbarComponent } from './pages/client/client-navbar.component.ts';
import { MallViewComponent } from './pages/mall/mall-view.component.ts';
import { ShopViewComponent } from './pages/shop/shop-view.component.ts';
import { ClientViewComponent } from './pages/client/client-view.component.ts';
import { ClientShopsViewComponent } from './pages/client/client-shops-view.component.ts';
import { ClientServicesViewComponent } from './pages/client/client-services-view.component.ts';
import { ClientEventsViewComponent } from './pages/client/client-events-view.component.ts';
import { ClientWalletViewComponent } from './pages/client/client-wallet-view.component.ts';
import { ChatComponent } from './components/chat.component.ts';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule, 
    FormsModule,
    SidebarComponent, 
    HeaderComponent, 
    ClientNavbarComponent,
    MallViewComponent,
    ShopViewComponent,
    ClientViewComponent,
    ClientShopsViewComponent,
    ClientServicesViewComponent,
    ClientEventsViewComponent,
    ClientWalletViewComponent,
    ChatComponent
  ],
  template: `
    <div [ngClass]="isClientMode() ? 'flex flex-col' : 'flex flex-row'" class="h-screen w-full overflow-hidden bg-lumina-cream font-jakarta">
      
      <!-- Admin/Shop Sidebar -->
      <app-sidebar 
        *ngIf="!isClientMode() && isLoggedIn()"
        [mode]="activeTab() === 'mall' || activeTab() === 'flux' || activeTab() === 'energy' ? 'admin' : 'shop'"
        [activeTab]="activeTab()" 
        [isOpen]="isSidebarOpen()"
        (tabChange)="activeTab.set($event)"
        (logout)="logout()"
        (close)="isSidebarOpen.set(false)"
      ></app-sidebar>

      <!-- Client Top Navbar -->
      <app-client-navbar 
        *ngIf="isClientMode()"
        [activeTab]="activeTab()"
        [isLoggedIn]="isLoggedIn()"
        (tabChange)="handleTabChange($event)"
        (onLoginRequest)="showLogin.set(true)"
        (logout)="logout()"
      ></app-client-navbar>

      <main class="flex-1 flex flex-col min-h-0 bg-lumina-cream relative overflow-hidden">
        <!-- Admin Header -->
        <app-header 
          *ngIf="!isClientMode() && isLoggedIn()"
          (toggleSidebar)="isSidebarOpen.set(!isSidebarOpen())"
        ></app-header>

        <div class="flex-1 overflow-y-auto custom-main-scroll relative h-full" id="main-scroll-container">
          
          <!-- Authentication Modal -->
          <div *ngIf="showLogin()" class="fixed inset-0 z-[100] flex items-center justify-center bg-lumina-dark/40 backdrop-blur-xl p-6">
            <div class="bg-white p-10 lg:p-14 rounded-[40px] shadow-3xl w-full max-w-lg animate-in fade-in zoom-in-95 duration-500 border border-lumina-olive/10">
              <div class="text-center mb-10">
                <div class="w-20 h-20 bg-lumina-rust rounded-[30px] flex items-center justify-center mx-auto mb-6 shadow-2xl rotate-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
                </div>
                <h2 class="text-4xl font-black text-lumina-olive font-outfit uppercase tracking-tighter">MasterOne Access</h2>
                <p class="text-lumina-tan text-[10px] font-black uppercase tracking-[0.4em] mt-3 opacity-60">MasterOne Secure Ecosystem</p>
              </div>

              <div class="space-y-6">
                <div class="space-y-2">
                  <label class="text-[10px] font-black uppercase tracking-[0.2em] text-lumina-olive/40 ml-4">Access Profile</label>
                  <select [(ngModel)]="loginRole" class="w-full px-8 py-5 bg-lumina-cream border border-lumina-olive/10 rounded-2xl font-bold outline-none focus:border-lumina-rust focus:ring-4 focus:ring-lumina-rust/5 transition-all appearance-none cursor-pointer text-lumina-olive text-sm">
                    <option value="client">V.I.P. Visitor (Wallet Access)</option>
                    <option value="mall">Mall Operations Director</option>
                    <option value="shop">Store Boutique Manager</option>
                  </select>
                </div>

                <div class="space-y-2" *ngIf="loginRole !== 'client'">
                  <label class="text-[10px] font-black uppercase tracking-[0.2em] text-lumina-olive/40 ml-4">Secure Passcode</label>
                  <input 
                    type="password" 
                    [(ngModel)]="loginPassword"
                    placeholder="••••••••"
                    (keydown.enter)="login()"
                    class="w-full px-8 py-5 bg-lumina-cream border border-lumina-olive/10 rounded-2xl font-bold outline-none focus:border-lumina-rust focus:ring-4 focus:ring-lumina-rust/5 transition-all text-lumina-olive text-sm"
                  />
                </div>

                <div *ngIf="loginRole === 'client'" class="p-8 bg-lumina-rust/5 rounded-3xl border border-lumina-rust/10 mb-2">
                   <p class="text-[11px] font-bold text-lumina-olive/60 leading-relaxed italic text-center">
                     Unlocking your MasterOne Visitor Profile grants access to private events, early sales, and our automated concierge.
                   </p>
                </div>

                <button (click)="login()" class="w-full py-6 bg-lumina-olive text-white rounded-2xl font-black uppercase tracking-[0.3em] hover:bg-lumina-rust transition-all shadow-2xl shadow-lumina-olive/20 active:scale-[0.98] text-xs">
                  {{ loginRole === 'client' ? 'Unlock MasterOne' : 'Authorize Entrance' }}
                </button>

                <div class="pt-8 border-t border-lumina-olive/5 text-center">
                  <button (click)="cancelLogin()" class="group flex items-center justify-center gap-3 mx-auto text-lumina-tan hover:text-lumina-rust transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="group-hover:-translate-x-2 transition-transform"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
                    <span class="text-[10px] font-black uppercase tracking-[0.3em]">Exit Protocol</span>
                  </button>
                </div>
              </div>
            </div>
          </div>

          <!-- Views Routing -->
          <div [ngClass]="isClientMode() ? 'w-full' : 'max-w-7xl mx-auto w-full p-6 md:p-12 lg:p-16'">
            <app-mall-view 
              *ngIf="activeTab() === 'mall'"
              [stats]="mallStats"
              [traffic]="trafficData"
              [suggestions]="mallSuggestions()"
              [loading]="loadingSuggestions()"
              (onRefresh)="fetchMallSuggestions()"
            ></app-mall-view>

            <app-shop-view 
              *ngIf="activeTab() === 'shop'"
            ></app-shop-view>

            <app-client-view *ngIf="activeTab() === 'client'"></app-client-view>
            <app-client-shops-view *ngIf="activeTab() === 'client-shops'"></app-client-shops-view>
            <app-client-services-view *ngIf="activeTab() === 'client-services'"></app-client-services-view>
            <app-client-events-view *ngIf="activeTab() === 'client-events'"></app-client-events-view>
            <app-client-wallet-view *ngIf="activeTab() === 'client-wallet'"></app-client-wallet-view>

            <div *ngIf="activeTab() === 'chat'" [ngClass]="isClientMode() ? 'p-6 md:p-16 max-w-5xl mx-auto' : ''">
              <app-chat
                [messages]="messages()"
                [isTyping]="isTyping()"
                (sendMessage)="handleSendMessage($event)"
                (clearChat)="messages.set([])"
              ></app-chat>
            </div>

            <div *ngIf="['flux', 'energy', 'sales', 'marketing'].includes(activeTab())" class="py-32 text-center animate-pulse">
               <div class="w-16 h-16 bg-lumina-tan/20 rounded-full mx-auto mb-6 flex items-center justify-center text-lumina-tan">
                 <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"/><path d="M16 16h5v5"/></svg>
               </div>
               <h2 class="text-2xl font-black text-lumina-olive font-outfit uppercase tracking-widest">Synchronizing MasterOne Data...</h2>
               <p class="text-lumina-olive/40 text-xs font-bold mt-4 uppercase tracking-[0.3em]">Connecting to MasterOne Cloud v3.1</p>
            </div>
          </div>
        </div>
      </main>

      <!-- Floating AI Button -->
      <button 
        *ngIf="isClientMode() && activeTab() !== 'chat'"
        (click)="activeTab.set('chat')"
        class="fixed bottom-10 right-10 w-16 h-16 bg-lumina-rust text-white rounded-2xl shadow-2xl flex items-center justify-center hover:scale-110 hover:bg-lumina-olive transition-all z-[60] group border-4 border-white/20 backdrop-blur-md"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="group-hover:rotate-12 transition-transform"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
        <span class="absolute right-full mr-6 bg-lumina-dark text-white px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest opacity-0 group-hover:opacity-100 transition-all scale-75 group-hover:scale-100 whitespace-nowrap shadow-2xl border border-white/10 pointer-events-none">
          MasterOne AI Concierge
        </span>
      </button>
    </div>
  `
})
export class AppComponent {
  private gemini = inject(GeminiService);
  
  activeTab = signal('client');
  isLoggedIn = signal(false);
  showLogin = signal(false);
  isSidebarOpen = signal(false);
  
  loginRole = 'client'; 
  loginPassword = '';

  isTyping = signal(false);
  messages = signal<Message[]>([]);
  mallSuggestions = signal<any[]>([]);
  loadingSuggestions = signal(false);

  isClientMode() {
    const publicTabs = ['client', 'client-shops', 'client-services', 'client-events', 'client-wallet', 'chat'];
    const tab = this.activeTab();
    if (tab === 'chat' && this.isLoggedIn() && (this.loginRole === 'mall' || this.loginRole === 'shop')) {
      return false;
    }
    return publicTabs.includes(tab);
  }

  handleTabChange(tab: string) {
    if (tab.endsWith('-section')) {
      if (this.activeTab() !== 'client') this.activeTab.set('client');
      setTimeout(() => {
        const element = document.getElementById(tab);
        const container = document.getElementById('main-scroll-container');
        if (element && container) element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 100);
      return;
    }

    if ((tab === 'mall' || tab === 'shop') && !this.isLoggedIn()) {
      this.loginRole = tab === 'mall' ? 'mall' : 'shop';
      this.showLogin.set(true);
    } else {
      this.activeTab.set(tab);
      const container = document.getElementById('main-scroll-container');
      if (container) container.scrollTop = 0;
    }
    this.isSidebarOpen.set(false);
  }

  login() {
    if (this.loginRole === 'client') {
      this.isLoggedIn.set(true); 
      this.showLogin.set(false);
      this.activeTab.set('client-wallet');
      return;
    }
    if (this.loginPassword.trim()) {
      this.isLoggedIn.set(true);
      this.showLogin.set(false);
      this.activeTab.set(this.loginRole === 'mall' ? 'mall' : 'shop');
      this.loginPassword = ''; 
    }
  }

  cancelLogin() {
    this.showLogin.set(false);
  }

  logout() {
    this.isLoggedIn.set(false);
    this.activeTab.set('client');
    this.messages.set([]);
    this.isSidebarOpen.set(false);
  }

  mallStats = [
    { label: 'Visits Today', value: '14.8k', trend: 15.4, icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/></svg>' },
    { label: 'Active Boutiques', value: '184', trend: 0.5, icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z"/></svg>' },
    { label: 'Grid Efficiency', value: '94%', trend: 2.1, icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>' },
    { label: 'Gross Revenue', value: '128.4k€', trend: 4.8, icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>' },
  ];

  trafficData = [
    { name: 'Mon', value: 55 }, { name: 'Tue', value: 48 }, { name: 'Wed', value: 72 },
    { name: 'Thu', value: 64 }, { name: 'Fri', value: 88 }, { name: 'Sat', value: 95 },
    { name: 'Sun', value: 42 },
  ];

  constructor() {
    effect(() => {
      if (this.activeTab() === 'mall' && this.mallSuggestions().length === 0) {
        this.fetchMallSuggestions();
      }
    });
  }

  async fetchMallSuggestions() {
    this.loadingSuggestions.set(true);
    try {
      const result = await this.gemini.getSmartSuggestions('Context: MasterOne shopping mall optimization Paris 2024.');
      this.mallSuggestions.set(result);
    } catch (e) {
      console.error(e);
    } finally {
      this.loadingSuggestions.set(false);
    }
  }

  async handleSendMessage(content: string) {
    const userMsg: Message = { id: Math.random().toString(), role: 'user', content, timestamp: Date.now() };
    this.messages.update(prev => [...prev, userMsg]);
    this.isTyping.set(true);

    try {
      const response = await this.gemini.analyzeContent(`Question: ${content}`);
      const aiMsg: Message = { id: Math.random().toString(), role: 'assistant', content: response, timestamp: Date.now() };
      this.messages.update(prev => [...prev, aiMsg]);
    } catch (e) {
      console.error(e);
    } finally {
      this.isTyping.set(false);
    }
  }
}
